version: 1
disable_existing_loggers: false
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout
loggers:
    pika_client:
        level: DEBUG
        handlers: [console]
        propagate: yes

    app:
        level: DEBUG
        handlers: [console]
        propagate: yes

    notifications:
        level: DEBUG
        handlers: [console]
        propagate: yes
